version: '3'
services:
  apiGateway:
    build:
      context: '.'
    image: api_gateway
    container_name:   apiGateway
    ports:
      - "9090:9090"
    depends_on:
      - 'rabbitmq'
    networks:
      - posts_app

  userService1:
    build:
      context: '../user_service/.'
    image: user_service
    container_name:   userService1
    ports:
      - "8081:8081"
    networks:
      - posts_app

  userService2:
    build:
      context: '../user_service/.'
    image: user_service
    container_name:   userService2
    ports:
      - "8082:8081"
    networks:
      - posts_app

  postService:
    build:
      context: '../post_service/.'
    image: post_service
    container_name:   postService
    ports:
      - "8083:8083"
    depends_on:
      - 'rabbitmq'
      - 'kafka'
    networks:
      - posts_app

  postNotificationService:
    build:
      context: '../post_notification_service/.'
    image: post_notification_service
    container_name: postNotificationService
    depends_on:
      - 'kafka'
      - 'zookeeper'
    ports:
      - "8084:8084"
    networks:
      - posts_app

  container:
    build:
      context: '../container/.'
    ports:
      - "3000:3000"
    container_name: container
    image: container
    stdin_open: true
    networks:
      - posts_app

  loginForm:
    build:
      context: '../login-form/.'
    ports:
      - "3001:3001"
    container_name: loginForm
    image: login_form
    stdin_open: true
    networks:
      - posts_app

  addPost:
    build:
      context: "../add-post/."
    ports:
      - "3002:3002"
    container_name: addPost
    image: add_post
    stdin_open: true
    networks:
      - posts_app

  viewPosts:
    build:
      context: "../view-posts/."
    ports:
      - "3003:3003"
    container_name: viewPosts
    image: view_posts
    stdin_open: true
    networks:
      - posts_app

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - posts_app

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - posts_app

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "postNotifications:1:1"
    networks:
      - posts_app

networks:
  posts_app:
